#include "vars.h"

extern void spawnMenu(int screenIndex);
extern void changeMenu(int newScreenIndex);
extern void moveSlot(void);
extern void initWarpMenu(void);
extern void playSFX(short sfxIndex);
extern void setPermFlag(short flagIndex);
extern void openStateMenu(void);
extern void openTimerSettingsMenu(void);
extern void openFileStateMainMenu(void);
extern void openFlagSubmenu(int screenIndex);
extern void toggleFlag(void);
extern void handleMapWarping(int map, int levelIndex);
extern int convertIDToIndex(short obj_index);
extern void* findActorWithType(int search_actor_type);

extern void destroyWatch(int slot);
extern void spawnWatch(int slot);
extern void colorWatch(char _red, char _green, char _blue, int slot);
extern void openWatchSnagMenu(void);

extern void warpToMap(void);
extern void openJapesMenu(void);
extern void openAztecMenu(void);
extern void openFactoryMenu(void);
extern void openGalleonMenu(void);
extern void openFungiMenu(void);
extern void openCavesMenu(void);
extern void openCastleMenu(void);
extern void openHelmRoolMenu(void);
extern void openIslesMenu(void);
extern void openOtherMapsMenu(void);

extern void openFlagsMainMenu(void);
extern void openFlagsKongMenu(void);
extern void openFlagsKeysinMenu(void);
extern void openFlagsKeyshaveMenu(void);
extern void openFlagsLevelintrosMenu(void);
extern void openFlagsLeveltnsMenu(void);
extern void openFlagsLevelbossMenu(void);
extern void openFlagsCutsceneMenu(void);
extern void openFlagsModifierMenu(void);
extern void openFlagsFTTMenu(void);
extern void openFlagsMiscMenu(void);
extern void openFlagsCustomMenu(void);
extern void openFlagsTBarrelMenu(void);

extern void openCheatsMenu(void);
extern void alterSkewAngle(void);
extern void cancelCutscene(void);
extern void gainControl(void);
extern void corruptGame(void);
extern void endMinigame(void);
extern void openGamemodeMenu(void);
extern void openTransformMenu(void);
extern void openMovesetInventoryMenu(void);
extern void openCrankyMenu(void);
extern void openFunkyMenu(void);
extern void openCandyMenu(void);
extern void openTogglesMenu(void);
extern void toggleSandstorm(void);
extern void toggleSpawnPrevention(void);
extern void toggleTBVoid(void);
extern void openSnagMenu(void);
extern void killBoss(void);
extern void toggleVisify(void);

extern void openSettingsMainMenu(void);
extern void openKongColorsMenu(void);
extern void openInputQuadrantMenu(void);
extern void openDPadLRMenu(void);
extern void openDPadDMenu(void);
extern void openVanillaVarsMenu(void);
extern void openHackVarsMenu(void);

extern void openActorMenu(void);
extern void openDebugMenu(void);

extern void openWatchMenu(void);
extern void endClose(void);
extern void toggleMenu(void);
extern void moveSlot(void);
extern void colorMenuSky(void);
extern void colorKong(void);
extern void levitate(void);
extern void closeMenuOnTransition(void);
extern void emergencyClose(void);
extern void confirmOption(void);
extern void menuShortcutButtons(void);
extern void startupSkip(void);
extern void closeWatchesOnTransition(void);
extern void openWatchesOnTransition(void);
extern void handleWatch(void);
extern void clampWatchFloats(void);
extern void tagAnywhere(void);
extern void initHack(void);
extern void handleTimer(void);
extern void hideInputDisplay(void);
extern void savestateHandler(void);
extern void shorthandSavestate(void);
extern void initRamViewerTab(void);
extern void ramViewUpdate(void);
extern void savestateLoadMapLoadVars(void);
extern void changeCustomFlagVariable(void);
extern void LToCancelCS(void);
extern void displaySavePrompt(void);
extern void clearSavePromptFlag(void);
extern void displayInput(void);
extern void openInputOnTransition(void);
extern void closeInputOnTransition(void);
extern void handlePositionSavestates(void);
extern void toggleFrameAdvanceState(void);
extern void initFrameAdvance(void);
extern void exitFrameAdvance(void);
extern void LToEndMinigame(void);
extern void forceStorySkip(void);
extern void setKRoolRound(void);
extern void handleAutophase(void);
extern void handleAutomoonkick(void);
extern void getSandstormAddress(void);
extern void handleSpawnPrevention(void);
extern void handleLToTBV(void);
extern void infiniteHealth(void);
extern void checkMapType(void);
extern void fileInit(void);
extern void controlWatchView(void);
extern void updateLoadedActorNoTextOverlayList(int callType);
extern void shouldRefreshTOMenu(void);

extern void loadSettings(void);
extern void saveSettings(void);
extern void resetSettings(void);
