#include "vars.h"

extern void moveSlot(void);
extern void playSFX(short sfxIndex);
extern void setPermFlag(short flagIndex);
extern void openStateMenu(void);
extern void openTimerSettingsMenu(void);
extern void openFileStateMainMenu(void);
extern void openFlagSubmenu(int screenIndex);
extern void toggleFlag(void);
extern void handleMapWarping(int map, int levelIndex);
extern int convertIDToIndex(short obj_index);
extern void* findActorWithType(int search_actor_type);

extern void openCheatsMenu(void);
extern void alterSkewAngle(void);
extern void cancelCutscene(void);
extern void gainControl(void);
extern void corruptGame(void);
extern void endMinigame(void);
extern void toggleSandstorm(void);
extern void toggleSpawnPrevention(void);
extern void toggleTBVoid(void);
extern void openSnagMenu(void);

extern void openWatchMenu(void);
extern void endClose(void);
extern void toggleMenu(void);
extern void moveSlot(void);
extern void colorMenuSky(void);
extern void colorKong(void);
extern void levitate(void);
extern void closeMenuOnTransition(void);
extern void emergencyClose(void);
extern void confirmOption(void);
extern void menuShortcutButtons(void);
extern void startupSkip(void);
extern void closeWatchesOnTransition(void);
extern void openWatchesOnTransition(void);
extern void handleWatch(void);
extern void clampWatchFloats(void);
extern void tagAnywhere(void);
extern void initHack(void);
extern void handleTimer(void);
extern void hideInputDisplay(void);
extern void savestateHandler(void);
extern void shorthandSavestate(void);
extern void initRamViewerTab(void);
extern void ramViewUpdate(void);
extern void savestateLoadMapLoadVars(void);
extern void changeCustomFlagVariable(void);
extern void LToCancelCS(void);
extern void displaySavePrompt(void);
extern void clearSavePromptFlag(void);
extern void displayInput(void);
extern void openInputOnTransition(void);
extern void closeInputOnTransition(void);
extern void handlePositionSavestates(void);
extern void toggleFrameAdvanceState(void);
extern void initFrameAdvance(void);
extern void exitFrameAdvance(void);
extern void LToEndMinigame(void);
extern void forceStorySkip(void);
extern void setKRoolRound(void);
extern void handleAutophase(void);
extern void handleAutomoonkick(void);
extern void handleSpawnPrevention(void);
extern void handleLToTBV(void);
extern void infiniteHealth(void);
extern void checkMapType(void);
extern void fileInit(void);
extern void controlWatchView(void);
extern void updateLoadedActorNoTextOverlayList(int callType);
extern void shouldRefreshTOMenu(void);

extern void loadSettings(void);
extern void saveSettings(void);
extern void resetSettings(void);
